version: '3.8'

services:
  redis-node-1:
    image: redis:7.2-alpine # Use uma versão recente do Redis
    container_name: redis-node-1
    command: redis-server --port 6379 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6378:6379"
      - "16379:16379" # Porta para o bus do cluster
    volumes:
      - ./redis-data/node-1:/data
    networks:
      - redis-cluster-net

  redis-node-2:
    image: redis:7.2-alpine
    container_name: redis-node-2
    command: redis-server --port 6380 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6380:6380"
      - "16380:16380"
    volumes:
      - ./redis-data/node-2:/data
    networks:
      - redis-cluster-net

  redis-node-3:
    image: redis:7.2-alpine
    container_name: redis-node-3
    command: redis-server --port 6381 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6381:6381"
      - "16381:16381"
    volumes:
      - ./redis-data/node-3:/data
    networks:
      - redis-cluster-net

  redis-node-4:
    image: redis:7.2-alpine
    container_name: redis-node-4
    command: redis-server --port 6382 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6382:6382"
      - "16382:16382"
    volumes:
      - ./redis-data/node-4:/data
    networks:
      - redis-cluster-net

  redis-node-5:
    image: redis:7.2-alpine
    container_name: redis-node-5
    command: redis-server --port 6383 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6383:6383"
      - "16383:16383"
    volumes:
      - ./redis-data/node-5:/data
    networks:
      - redis-cluster-net

  redis-node-6:
    image: redis:7.2-alpine
    container_name: redis-node-6
    command: redis-server --port 6384 --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "6384:6384"
      - "16384:16384"
    volumes:
      - ./redis-data/node-6:/data
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    driver: bridge